<a href="https://colab.research.google.com/github/bogicho/FlyAI-5/blob/main/Day4_AI_%EC%86%8C%EA%B0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

붓꽃(iris)
- 꽃잎(petal)과 꽃받침(sepal)의 폭과 길이
- 식물학자의 품종 분류
 - setosa
 - versicolor
 - virginica

#**1. 붓꽃 데이터 분류 프로세스**
<br>
- 데이터셋 분리 : 데이터를 학습 데이터와 테스트 데이터로 분리
- 모델 학습 : 학습 데이터를 기반으로 ML 알고리즘을 적용해서 모델을 학습
- 예측 수행 : 학습된 모델을 사용해서 테스트 데이터를 예측
- 평가 : 예측된 결과값과 테스트 데이터의 실제 결과값을 비교해서 모델 성능을 평가


In [ ]:
# 사이킷런 버전 확인 !pip install sklearn
import sklearn
print(sklearn.__version__)

1.2.2


### (1-1) 붓꽃 예측을 위한 사이킷런 필요 모듈 로딩

In [ ]:
# 내장 붓꽃 데이터셋
from sklearn.datasets import load_iris
# 의사결정트리 모델
from sklearn.tree import DecisionTreeClassifier
# 데이터셋 분리 함수
from sklearn.model_selection import train_test_split
import pandas as pd

### (1-2) 붓꽃 데이터셋 로딩

In [ ]:
# 붓꽃 데이터셋 로딩
iris = load_iris()

# 딕셔너리 형태
print(type(iris))
iris

<class 'sklearn.utils._bunch.Bunch'>


{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [ ]:
# data: 4개의 피처(feature)들로 이루어진 numpy 배열
iris_data = iris.data
iris_data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
# target: 붓꽃 데이터셋의 레이블(결정 값) 데이터로 된 numpy배열
iris_label = iris.target
print('iris target값:', iris_label)
print('iris target명:', iris.target_names)


iris target값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target명: ['setosa' 'versicolor' 'virginica']


In [ ]:
# 붓꽃 데이터셋을 자세히 보기 위해 DataFrame으로 변환
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [ ]:
# 레이블 컬럼 추가
iris_df['label'] = iris_label
print(iris_df)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     label  
0        0  
1

In [ ]:
iris_df.head(3)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

### (1-3) 학습데이터와 테스트 데이터 셋 분리

In [ ]:
# 데이터셋의 20%를 테스트 데이터로 사용
X_train, X_test, y_train, y_test = train_test_split(iris_data,
                                                    iris_label,
                                                    test_size=0.3,
                                                    random_state=10)

### (1-4) 학습 데이터 셋으로 학습(Train)

In [ ]:
# DecisionTreeClassifier 객체 생성
dt_clf = DecisionTreeClassifier(random_state=1)

# 학습 수행
dt_clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=15)

### (1-5) 테스트 데이터셋으로 예측(Predict)

In [ ]:
# 학습이 완료된 DecisionTreeClassifier 객체에서 테스트 데이터 세트로 예측 수행.
pred = dt_clf.predict(X_test)
pred

array([0, 1, 1, 0, 0, 1, 2, 1, 1, 2, 2, 1, 1, 1, 2, 0, 1, 2, 0, 1, 1, 0,
       1, 1, 0, 0, 2, 2, 2, 1, 0, 2, 1, 2, 0, 0, 2, 0, 0, 1, 2, 0, 0, 1,
       2])

### (1-6) 예측 정확도 **평가**

In [ ]:
from sklearn.metrics import accuracy_score
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test,pred)))

#print(accuracy_score(y_test,pred))

예측 정확도: 0.9778


# **2. 교차검증을 이용한 분꽃 데이터  검증 평가**
##**2-1. K-Fold 교차검증**
  - K개의 폴드 세트를 만들어서 K번의 학습과 검증 평가를 반복 수행
  - 폴드세트 : 데이터셋을 K개의 세트로 나눈 것.
  - 매 학습마다 이미 나눠진 폴드세트 중 하나의 세트를 검증 세트로 정하고 나머지를 학습폴드세트로 하여 학습과 검증평가 진행
  - 검증 평가 값들의 평균을 통해 교차 검증 최종 평가

###(1) 라이브러리

In [ ]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

###(2) 데이터 로딩

In [ ]:
# 붓꽃 데이터셋 호출
iris = load_iris()
features = iris.data
label = iris.target

###(3) 의사결정트리 모델 객체 생성

In [ ]:
# 의사결정트리 모델 객체 생성
dt_clf = DecisionTreeClassifier()

In [ ]:
# 5개의 폴드 세트로 분리하는 KFold 객체 생성
kfold = KFold(n_splits=7)

In [ ]:
# 폴드 세트별 정확도를 담을 리스트 객체 생성
cv_accuracy = []

In [ ]:
#반복횟수 확인용
n_iter = 0

###(4) 교차검증

In [ ]:
# KFold 객체의 split() 호출하면 폴드 별 학습용, 검증용 테스트의 row 인덱스를 array로 반환
for train_index, test_index  in kfold.split(features):
    # kfold.split()으로 반환된 인덱스를 이용하여 학습용, 검증용 테스트 데이터 추출
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]

    #학습 및 예측
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1

    # 반복 시 마다 정확도 측정
    accuracy = np.round(accuracy_score(y_test,pred), 4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print('\\n#{0} 교차 검증 정확도 :{1}, 학습 데이터 크기: {2}, 검증 데이터 크기: {3}'.format(n_iter, accuracy, train_size, test_size))
    print('#{0} 검증 세트 인덱스:{1}'.format(n_iter,test_index))

    cv_accuracy.append(accuracy)


\n#1 교차 검증 정확도 :1.0, 학습 데이터 크기: 128, 검증 데이터 크기: 22
#1 검증 세트 인덱스:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]
\n#2 교차 검증 정확도 :1.0, 학습 데이터 크기: 128, 검증 데이터 크기: 22
#2 검증 세트 인덱스:[22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43]
\n#3 교차 검증 정확도 :1.0, 학습 데이터 크기: 128, 검증 데이터 크기: 22
#3 검증 세트 인덱스:[44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65]
\n#4 교차 검증 정확도 :0.7619, 학습 데이터 크기: 129, 검증 데이터 크기: 21
#4 검증 세트 인덱스:[66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86]
\n#5 교차 검증 정확도 :0.9524, 학습 데이터 크기: 129, 검증 데이터 크기: 21
#5 검증 세트 인덱스:[ 87  88  89  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104
 105 106 107]
\n#6 교차 검증 정확도 :1.0, 학습 데이터 크기: 129, 검증 데이터 크기: 21
#6 검증 세트 인덱스:[108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128]
\n#7 교차 검증 정확도 :0.9524, 학습 데이터 크기: 129, 검증 데이터 크기: 21
#7 검증 세트 인덱스:[129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146
 147 148 149]


###(5) 정확도

In [ ]:
# 개별 iteration별 정확도를 합하여 평균 정확도 계산
print('\\n## 평균 검증 정확도:', np.mean(cv_accuracy))

\n## 평균 검증 정확도: 0.9523857142857143


##**2-2. Stratified K-Fold**

— 불균형한 레이블 분포도를 가진 데이터셋을 위한 K폴드 방식

  - 학습 데이터와 검증 데이터 세트가 가지는 레이블 분포도가 유사하도록 폴드세트를 구성.
  - 예를 들어 신용카드 사기를 잡아내야 하는데 그 비율이 100건 중 10건이라면, 어떤 데이터셋에는 사기인 경우가 하나도 없고 어떤 데이터셋에는 사기인 레이블이 몰려있지 않도록 폴드세트의 레이블 구성 비율을 동일하게 나눔.
  - 대부분 분류 모델의 경우 stratified k-fold를 사용하는 것이 좋다


###(2-1) 라이브러리 호출

In [ ]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import StratifiedKFold
import numpy as np
import pandas as pd

###(2-2) 데이터셋 로딩

In [ ]:
# 붓꽃 데이터셋 호출
iris = load_iris()

###가. 데이터 레이블 분포확인

In [ ]:
# 레이블 분포 확인
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['label']=iris.target
iris_df['label'].value_counts()  # 0:50, 1:50, 2:50


label
0    50
1    50
2    50
Name: count, dtype: int64

###(2-3) 3개의 폴드셋트 객체 생성

In [ ]:
# 3개의 폴드세트로 나누는 Stratified K-Fold 객체 생성
skf = StratifiedKFold(n_splits=3)
# 반복횟수 확인용
n_iter=0

###가. 레이블 분포 확인

In [ ]:
# 데이터셋 별 레이블 분포 확인 -> 균등한 비율로 분포가 된 것을 확인가능
for train_index, test_index in skf.split(iris_df, iris_df['label']):
    n_iter += 1
    label_train= iris_df['label'].iloc[train_index]
    label_test= iris_df['label'].iloc[test_index]
    print('## 교차 검증: {0}'.format(n_iter))
    print('학습 레이블 데이터 분포:\\n', label_train.value_counts())
    print('검증 레이블 데이터 분포:\\n', label_test.value_counts())

## 교차 검증: 1
학습 레이블 데이터 분포:\n label
2    34
0    33
1    33
Name: count, dtype: int64
검증 레이블 데이터 분포:\n label
0    17
1    17
2    16
Name: count, dtype: int64
## 교차 검증: 2
학습 레이블 데이터 분포:\n label
1    34
0    33
2    33
Name: count, dtype: int64
검증 레이블 데이터 분포:\n label
0    17
2    17
1    16
Name: count, dtype: int64
## 교차 검증: 3
학습 레이블 데이터 분포:\n label
0    34
1    33
2    33
Name: count, dtype: int64
검증 레이블 데이터 분포:\n label
1    17
2    17
0    16
Name: count, dtype: int64


###나. 의사결정트리 모델 객체 생성

In [ ]:
# 의사결정트리 모델 객체 생성
dt_clf = DecisionTreeClassifier()

skfold = StratifiedKFold(n_splits=3)
n_iter=0
cv_accuracy=[]

###(2-4). 학습용/ 검증용 데이터 분리

In [ ]:
# StratifiedKFold의 split() 호출시 반드시 레이블 데이터 셋도 추가 입력 필요
for train_index, test_index  in skfold.split(features, label):
    # split()으로 반환된 인덱스를 이용하여 학습용, 검증용 테스트 데이터 추출
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]

    #학습 및 예측
    dt_clf.fit(X_train , y_train)
    pred = dt_clf.predict(X_test)

    # 반복 시 마다 정확도 측정
    n_iter += 1
    accuracy = np.round(accuracy_score(y_test,pred), 4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]

    print('\\n#{0} 교차 검증 정확도 :{1}, 학습 데이터 크기: {2}, 검증 데이터 크기: {3}'
          .format(n_iter, accuracy, train_size, test_size))
    print('#{0} 검증 세트 인덱스:{1}'.format(n_iter,test_index))
    cv_accuracy.append(accuracy)

\n#1 교차 검증 정확도 :0.98, 학습 데이터 크기: 100, 검증 데이터 크기: 50
#1 검증 세트 인덱스:[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]
\n#2 교차 검증 정확도 :0.92, 학습 데이터 크기: 100, 검증 데이터 크기: 50
#2 검증 세트 인덱스:[ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]
\n#3 교차 검증 정확도 :1.0, 학습 데이터 크기: 100, 검증 데이터 크기: 50
#3 검증 세트 인덱스:[ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]


###(2-5) 정확도

In [ ]:
# 교차 검증별 정확도 및 평균 정확도 계산
print('\\n## 교차 검증별 정확도:', np.round(cv_accuracy, 4))
print('## 평균 검증 정확도:', np.mean(cv_accuracy))

\n## 교차 검증별 정확도: [0.98 0.92 1.  ]
## 평균 검증 정확도: 0.9666666666666667


##**2-3. cross_val_score()**
- 교차검증을 보다 간편하게 해주는 API. 위에서 했던 for문을 통한 반복을 생략시켜준다.
- 주요 파라미터
  - estimator : 분류/회귀 모델 객체
  - X : 피처 데이터셋
  - y : 레이블 데이터셋
  - scoring : 평가기준 (평균, 정확도 등)
  - cv : 교차검증 횟수
  - from sklearn.tree impor

###(1) 라이브러리

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score , cross_validate
from sklearn.datasets import load_iris
import numpy as np

###(2) 데이터셋 로딩

In [ ]:
iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)
dt_clf

DecisionTreeClassifier(random_state=156)

###(3) 피처 데이터셋

In [ ]:
# 피처 데이터셋
data = iris_data.data
# 레이블 데이터셋
label = iris_data.target
label

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

###(4) 정확도, 교차검증셋 3개

In [ ]:
# 성능 지표는 정확도(accuracy) , 교차 검증 세트는 3개
scores = cross_val_score(dt_clf , data , label , scoring='accuracy',cv=3)
print('교차 검증별 정확도:',np.round(scores, 4))
print('평균 검증 정확도:', np.round(np.mean(scores), 4))

교차 검증별 정확도: [0.98 0.94 0.98]
평균 검증 정확도: 0.9667


##**2-4. GridSearchCV**
— 교차검증과 하이퍼 파라미터 튜닝을 한 번에 해주는 모듈
  - Grid, 격자처럼 모든 경우의 수를 촘촘하게 확인
  - 예를들어 grid_parameters = {‘max_depth’:[1,2,3], ‘min_samples_split’:[2,3]} 이라면 파라미터 별 경우의 수가 3 x 2 =6, 여기에 교차검증을 3회 한다고 하면 6 x 3, 총 18회의 학습/검증을 수행하게 된다.

###(1) 라이브러리 호출

In [ ]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.metrics import accuracy_score
import pandas as pd

###(2) 데이터셋 로딩

In [ ]:
iris = load_iris()

dtree = DecisionTreeClassifier()
dtree

DecisionTreeClassifier()

###(3) 학습데이터와 검증 데이터 셋 분리


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target,
                                                    test_size=0.2, random_state=121)

####가. parameter들을 dictionary 형태로 설정

In [ ]:
parameters = {'max_depth':[1, 2, 3], 'min_samples_split':[2,3]}


###(4)  하이퍼 파라미터들을 3개의 train, test fold 로 나누어서 테스트

In [ ]:
# param_grid의 하이퍼 파라미터들을 3개의 train, test fold 로 나누어서 테스트 수행 설정
# refit: True면 학습/검증이 모두 끝난 후 가장 좋은 파라미터 설정으로 재학습 시킴 (디폴트 True)
grid_dtree = GridSearchCV(dtree, param_grid=parameters, cv=3, refit=True, return_train_score=True)
grid_dtree

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [1, 2, 3], 'min_samples_split': [2, 3]},
             return_train_score=True)

###(5) 평가

In [ ]:
# 붓꽃 Train 데이터로 param_grid의 하이퍼 파라미터들을 순차적으로 학습/평가 .
grid_dtree.fit(X_train, y_train)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [1, 2, 3], 'min_samples_split': [2, 3]},
             return_train_score=True)

####가. GridSearchCV 결과

In [ ]:
# GridSearchCV 결과는 cv_results_ 라는 딕셔너리로 저장됨
# 이를 DataFrame으로 변환
scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params', 'mean_test_score', 'rank_test_score',
           'split0_test_score', 'split1_test_score', 'split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

###(6) 정확도

In [ ]:
print('GridSearchCV 최적 파라미터:', grid_dtree.best_params_)
print('GridSearchCV 최고 정확도: {0:.4f}'.format(grid_dtree.best_score_))

GridSearchCV 최적 파라미터: {'max_depth': 3, 'min_samples_split': 2}
GridSearchCV 최고 정확도: 0.9750


####가. predict()를 통해 최적의 하이퍼 파라미터 설정으로 예측

In [ ]:
# refit=True로 설정된 GridSearchCV 객체는 fit()으로 학습이 완료된 Estimator를 포함하고 있음
# 즉, predict()를 통해 최적의 하이퍼 파라미터 설정으로 예측도 가능.
pred = grid_dtree.predict(X_test)
print('테스트 데이터 세트 정확도: {0:.4f}'.format(accuracy_score(y_test,pred)))

테스트 데이터 세트 정확도: 0.9667


####나. GridSearchCV의 refit으로 이미 학습이 된 estimator

In [ ]:
# 만약 refit=False 였다면 다음과 같이하여 같은 결과를 볼 수 있다
# GridSearchCV의 refit으로 이미 학습이 된 estimator 반환
estimator = grid_dtree.best_estimator_
print('refit으로 이미 학습된 estimator : ', estimator)

refit으로 이미 학습된 estimator :  DecisionTreeClassifier(max_depth=3)


####다. best_estimator

In [ ]:
# GridSearchCV의 best_estimator_는 이미 최적 하이퍼 파라미터로 학습이 됨
pred = estimator.predict(X_test)
print('테스트 데이터 세트 정확도: {0:.4f}'.format(accuracy_score(y_test,pred)))

테스트 데이터 세트 정확도: 0.9667


#**3.데이터 전처리(Preprocessing)**

###(1) 라이브러리 로딩

In [ ]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
import numpy as np
import pandas as pd


###(2) 레이블링 인코딩

In [ ]:
### 레이블 인코딩
items=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

# LabelEncoder를 객체로 생성한 후, fit( ) 과 transform( ) 으로 label 인코딩 수행.
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

print(labels)  # 인코딩 변환값: [0 1 4 5 3 3 2 2]
print(encoder.classes_)  # 인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터']
print(encoder.inverse_transform([4, 5, 2, 0, 1, 1, 3, 3]))  # 디코딩 원본 값: ['전자렌지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']

[0 1 4 5 3 3 2 2]
['TV' '냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터']
['전자렌지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


###(3) 원핫인코딩(사이킷런)

In [ ]:
### 원핫 인코딩 (사이킷런)
# 먼저 숫자값으로 변환을 위해 LabelEncoder로 변환
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

####(가) 2차원데이터로 변환

In [ ]:
# 2차원 데이터로 변환
labels = labels.reshape(-1,1)

####(나) 원-핫 인코딩 적용

In [ ]:
#원-핫 인코딩 적용
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)

print(oh_labels.toarray())
print(oh_labels.shape)  # (8, 6)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
(8, 6)


####(다) 원핫 인코딩(판다스)

In [ ]:
# 판다스 원핫인코딩
df = pd.DataFrame({'item':['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서'] })
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자렌지  item_컴퓨터
0     True     False    False     False      False     False
1    False      True    False     False      False     False
2    False     False    False     False       True     False
3    False     False    False     False      False      True
4    False     False    False      True      False     False
5    False     False    False      True      False     False
6    False     False     True     False      False     False
7    False     False     True     False      False     False

###(4) 피처 스케일링

In [ ]:
# 정규화 - StandardScaler
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris

###(5) 붓꽃 데이터 로딩

In [ ]:
# 붓꽃 데이터 셋을 로딩하고 DataFrame으로 변환
iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

print(iris_df.mean())
print(iris_df.var())

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


###(6) StandardScaler객체 생성

In [ ]:
# StandardScaler객체 생성
scaler = StandardScaler()
# StandardScaler 로 데이터 셋 변환, fit( ) 과 transform( ) 호출
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

#transform( )시 scale 변환된 데이터 셋이 numpy ndarry로 반환되어 이를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print(iris_df_scaled.mean())
print(iris_df_scaled.var())

sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


###(7)표준화

In [ ]:
# 표준화 - MinMaxScaler
from sklearn.preprocessing import MinMaxScaler

# MinMaxScaler객체 생성
scaler = MinMaxScaler()

# MinMaxScaler 로 데이터 셋 변환, fit() 과 transform() 호출.
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

# transform()시 scale 변환된 데이터 셋이 numpy ndarry로 반환되어 이를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print(iris_df_scaled.min())
print(iris_df_scaled.max())

sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


#**4.평가(Evaluation)**

- 분류성능 평가지표
  - 오차행렬 (Confusion Matrix)
    - 이진분류의 예측 오류가 얼마인지와 더불어 어떤 유형의 예측 오류(Type I, II Error)가 발생하고 있는 지를 나타내는 지표
      - [[TN, FP], [FN, TP]] 형태로 결과 반환
      - False Positive, 실제로는 거짓일 때 참을 반환한 경우 → Type I Error
      - False Negative, 실제로는 참인데 거짓을 반환한 경우 → Type II Error
      - 정확도 = 예측 결과와 실제 값이 동일한 건수/전체 데이터 수 = (TN + TP)/(TN + FP + FN + FP)

###(1) 정확도 (Accuracy)
  - 전체 데이터 대비 예측 결과가 맞는 데이터의 비율을 %로 표현
  - 직관적으로 모델 예측 성능을 나타내는 평가 지표
  - 하지만 이진 분류(True or False)에서는 모델 성능을 왜곡할 수 있기 때문에 정확도만 가지고 성능을 평가하지는 않는다. 특히, 불균형한 레이블 값 분포에서 적합한 평가 지표가 되지 못한다.


In [ ]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, pred)

###(2) 정밀도 & 재현율
- 정밀도 (Precision)
  - 예측을 Positive로 한 대상 중 예측과 실제 값이 Positive로 일치한 데이터의 비율
  - ⇒ 정밀도 = TP / (FP + TP)
  - precision_score() 메서드로 확인
- 재현율 (Recall)
  - 실제 값이 Positive인 대상 중에 예측과 실제 값이 Positive로 일치한 데이터의 비율
  - ⇒ 재현율 = TP / (FN + TP)
  - recall_score() 메서드로 확인
- 정밀도와 재현율의 트레이드오프
  - 업무에 따라 정밀도와 재현율의 중요도는 상대적일 수 있다
  - 정밀도가 중요한 경우 : 스팸 메일을 거르는 시스템의 경우 정상 메일(Negative)을 스팸(Positive)으로 분류하면 안된다. 즉, False Positive 혹은 Type I Error를 일으키면 안되는 경우 정밀도가 더 중요한 지표가 된다.
  - 재현율이 중요한 경우 : 암 진단 처럼 실제로 양성(Positive)인 결과를 음성(Negative)로 판별해버리는 경우가 더 치명적인 경우. 즉, False Negative 혹은 Type II Error를 일으키면 안되는 경우 재현율이 더 중요한 지표가 된다.
  - 분류 업무 특성상 위 처럼 정밀도 또는 재현율이 특별히 강조돼야 할 경우 분류 결정 임계값 (Threshold)을 조정해 수치를 높일 수 있다.
  - Estimator 객체의 predict_proba() 메소드로 분류 결정 예측 확률 반환
  - 임계값이 낮아질 수록 Positive로 예측할 확률이 높아진다 → 재현율 증가
  - 정밀도와 재현율은 상호 보완적인 평가 지표이기 때문에 어느 한쪽을 강제로 높이면 다른 하나의 수치가 떨어지기 쉽다. 이를 정밀도/재현율의 트레이드오프(Trade-off)라고 한다.
  - precision_recall_curve() 함수를 통해 임계값에 따른 정밀도, 재현율의 변화값 확인

###(3) F1 Score
- 정밀도와 재현율의 맹점 : 임계값을 필요에 따라 조정하면 얼마든지 정밀도 또는 재현율을 100%로 조작할 수 있다. 즉, 두 지표의 밸런스를 확인할 필요가 있다.
- ⇒ F1 스코어는 정밀도와 재현율을 결합한 지표로 정밀도와 재현율이 어느 한쪽으로 치우치지 않는 수치를 나타낼 때 상대적으로 높은 값을 갖는다.
- 사이킷런에서 f1_score() 함수로 확인 가능

###(4) ROC 곡선과 AUC
- ROC 곡선 (Receiver Operation Characteristic Curve)
  — FPR(False Positive Rate)이 변할 때 TPR(True Positive Rate, =재현율)이 어떻게 변하는지 나타내는 곡선
  - TPR, 즉 재현율은 “민감도”로도 불린다
  - roc_curve(y_true, y_score)
    - y_true : 실제 클래스 값
    - y_score : predict_proba()의 반환 값 중 positive 예측 확률을 사용
  - → fpr, tpr, thresholds 반환

- AUC (Area Under Curve)<br>
  - ROC곡선 아래의 면적을 구한 것. 면적이 1에 가까울 수록 좋은 수치
    - roc_auc_score(y_true, y_score)
      - 사용되는 파라미터는 roc_curve()와 동일
    - → AUC 스코어 값 반환

#5. Decision Tree 학습과 시각화
- decision Tree란 무엇인가?
  - 의사결정 규칙을 나무 구조로 나타내어 전체 자료를 몇 개의 작은 집단으로 나누어서 분석하는 기법이다.
  - SVM 처럼 결정트리(decision tree)는 분류 및 회귀가 가능한 머신러닝 알고리즘이다.
  - 매우 복잡한 데이터셋도 학습할 수 있는 강력한 알고리즘
  - 최근에 많이 사용하는 랜덤 포레스트의 기본 구성 요소이다.

In [ ]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz
from subprocess import check_call

iris = load_iris()
x = iris.data[:,2:] # 꽃잎의 길이, 너비
y = iris.target



In [ ]:
# decision tree 모형 인스턴스 생성 및 하이퍼파라미터(depth) = 3
tree_model = DecisionTreeClassifier(max_depth=3)
tree_model.fit(x,y)

export_graphviz(
    tree_model, # 학습한 모형
    out_file = './iris_tree_model.dot', # .dot 파일 저장 위치
    feature_names = iris.feature_names[2:], # 사용한 변수 이름
    class_names = iris.target_names, # 예측할 타겟 클래스 이름
    rounded=True, # 사각형 끝을 둥글게
    filled=True # 사각형 안 색깔 채우기
)


In [ ]:
# 예측한 모형 png로 바꿔서, 시각화 하기
check_call(['dot','-Tpng','iris_tree_model.dot','-o','OutputFile.png'])

0

###(가) Decision Tree 클래스 확률 추정
- 결정 트리도 한 샘플이 특정 클래스에 속할 확률을 추정토록 할 수 있다.
- 위 과정처럼 어떤 샘플이 각 조건에 따라서 리프 노드로 분기를 하고, 해당 노드에 클래스 비율이 곧 클래스 확률이 된다.


In [ ]:
tree_model.predict_proba([[3.1,2]])

array([[0.        , 0.33333333, 0.66666667]])

In [ ]:
# 인덱스 2번이 가장 높은 0.6666667이라는 확률값을 산출하여 2번 클래스를 예측한다.
tree_model.predict([[3.1,2]])

array([2])

###(나) 결정트리를 활용한 회귀
- decision tree(결정 트리)를 활용하여 회귀문제 또한 해결할 수 있다.


In [ ]:
from sklearn.tree import DecisionTreeRegressor

# max_depth = 3
tree_model = DecisionTreeRegressor(max_depth=3)
tree_model.fit(x,y)

export_graphviz(
    tree_model, # 학습한 모형
    out_file = './iris_tree_model_reg.dot', # .dot 파일 저장 위치
    feature_names = iris.feature_names[2:], # 사용한 변수 이름
    rounded=True, # 사각형 끝을 둥글게
    filled=True # 사각형 안 색깔 채우기
)

# 예측한 모형 png로 바꿔서, 시각화 하기
check_call(['dot','-Tpng','iris_tree_model_reg.dot','-o','OutputFile_reg.png'])

0